### ISSUE TITLE
Footer must be visible only in the bottom of page

### ISSUE THREAD

**Issue by Yasinaaa** [Zakyat/zakyat-frontend#16] opened 2020-05-13 10:45 UTC

**Comment by Yasinaaa** [comment] 2020-05-13 10:47
Expectation
<img width="1161" alt="Screenshot 2020-05-13 at 13 44 47" src="https://user-images.githubusercontent.com/10158025/81803325-2fb36700-9520-11ea-9946-9d6e58f7d2e8.png">

Reality
<img width="1669" alt="Screenshot 2020-05-13 at 13 44 29" src="https://user-images.githubusercontent.com/10158025/81803338-36da7500-9520-11ea-82f1-8467e33410b5.png">

**Comment by aabounegm** [comment] 2020-05-14 21:02
No need to move cards to Done manually. They will be moved as soon as the pull request that resolves the issue is merged. That is the point of the card automation

**Closed** 2020-06-06 21:41 UTC
